spring:
  cloud:
    gateway:
      routes:
        - id: catalogue-service-route
          uri: lb://webstore-catalogue-service
          predicates:
            - Host=catalogue.api.172.29.64.1.nip.io**
        - id: feedback-service-route
          uri: lb://webstore-feedback-service
          predicates:
            - Host=feedback.api.172.29.64.1.nip.io**
        - id: superviser-arm-route
          uri: lb://webstore-superviser-arm
          predicates:
            - Host=manager.172.29.64.1.nip.io**
        - id: customer-app-route
          uri: lb://webstore-customer-app
          predicates:
            - Host=customer172.29.64.1.nip.io**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.29.64.1:8082/realms/webstore
      client:
        provider:
          keycloak:
            issuer-uri: http://172.29.64.1:8082/realms/webstore
        registration:
          discovery:
            provider: keycloak
            client-id: api-gateway
            client-secret: ltSRwZUEheA2BPx9tAE2VwiLCA6gwfaE
            authorization-grant-type: client_credentials
            scope:
              - discovery
  application:
    name: webstore-api-gateway
  boot:
    admin:
      client:
        enabled: false
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://172.29.64.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    hostname: 172.29.64.1
  client:
    service-url:
      defaultZone: http://172.29.64.1:8761/eureka/
    registryFetchIntervalSeconds: 1
